#!/bin/bash
set -xeo pipefail

GIT_DIR=$(pwd)
WORK_DIR=$(dirname $GIT_DIR)

read oldrev newrev ref

(
  cd $WORK_DIR
  git --work-tree=$WORK_DIR checkout -f $newrev

  echo "Updating Build Pack"
  git clone https://github.com/heroku/heroku-buildpack-ruby.git .bp

  env -i PATH=$PATH \
    .bp/bin/compile $WORK_DIR $GIT_DIR/.cache
  [ $? -ne 0 ] && { echo Heroku push rejected, failed to compile app; exit 1; }

  mkdir -p .log
  touch .log/finished
)