#!/usr/bin/env -i /bin/bash
# set up logging; stdout is tee'd to compile log, stderr appends to debug log
LOG_DIR=$(dirname $PWD)/.log
exec 1> >(tee -a $LOG_DIR/compile.log)
exec 2> >(cat >> $LOG_DIR/debug.log)

# main script
set -xo pipefail
source $LOG_DIR/build_env

GIT_DIR=$(pwd)
WORK_DIR=$(dirname $GIT_DIR)
BP_DIR=$WORK_DIR/.bp

touch $LOG_DIR/started
echo "-----> Heroku receiving push"

read oldrev newrev ref
git --work-tree=$WORK_DIR checkout -f $newrev

echo "-----> Updating buildpack..."
git clone $BUILDPACK_URL $BP_DIR 1>&2

# run detect / compile / release in a clean environment
_env() { env -i PATH=$PATH "$@"; }
echo "-----> $(_env $BP_DIR/bin/detect $WORK_DIR) app detected"
_env $BP_DIR/bin/compile $WORK_DIR $GIT_DIR/.cache ; STATUS=$?
_env $BP_DIR/bin/detect  $WORK_DIR &> $LOG_DIR/detect.log
_env $BP_DIR/bin/release $WORK_DIR &> $LOG_DIR/release.log

if [ $STATUS != 0 ]; then
  echo "!     Heroku push rejected"
else
  echo "-----> Compiled slug size is 628K"
fi

echo $STATUS > $LOG_DIR/finished
exit $STATUS